config/routes.rb
Rails.application.routes.draw do
get 'checkout/index'
post 'checkout/confirm'
get 'checkout/confirm' => 'checkout#receipt'

  resources :order_items
  resources :orders
  resources :food_items
get 'checkout' => 'checkout#index'

get 'menu' => 'home#menu'
get 'contact_us' => 'home#contact_us'
	root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
    def self.search(search)
    where('name LIKE ?', "%#{search}%")
    end

    def self.filter(filter)
    where('cruisine LIKE ?', "%#{filter}%")
    end

    def self.searchItem(item_id)
    where('id = ?',"%#{item_id}")
    end
end

app/models/order.rb
class Order < ApplicationRecord
    validates :name, presence: true
    has_many :order_items

    def total_price
        order_items.map{|e| e.food_item.price*e.quantity}.sum
    end

    def apply_discount(discount_percent)
        order_items.map{|e| e.food_item.price*e.quantity}.sum*discount_percent
    end

    def self.last_open
        where(confirmed_at: nil).last
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order

  validates :food_item, :order, presence: true
end

app/models/section.rb
class Section < ApplicationRecord
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    has_many :food_items
    def self.generate_defaults
        %w(Breakfast Lunch Dinner Supper).each do |name|
            Section.find_or_create_by(name: name)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  def current_order
#    @current_order = Order.last
#    unless @current_order
#      @current_order = Order.create! name: "Guess", address: "unknown"
#    end
#    @current_order
    @current_order = Order.last_open || Order.create!(name: "Guess", address: "unknown")
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
    @order = current_order
  end

  def confirm
    @order = current_order
    @order.shipping_cost = 20
		if order_params[:discount_code].to_s.length > 0
			if order_params[:discount_code].to_s=="CODERSCHOOL"
				@order.discount_code = "CODERSCHOOL"
				@order.origin_price = @order.total_price
				@order.discounted_price = @order.apply_discount(0.5)
				@order.grand_total = @order.discounted_price.to_f + @order.shipping_cost.to_f
				@order.confirmed_at = Time.now
				if @order.save
					render 'receipt'
				else
					flash[:error] = @order.errors.full_messages.to_sentence
					render 'index'
				end
			else
				@order.errors.add(:discount_code,:invalid,message: "Invalid Discount Code") 
				flash[:error] = @order.errors.full_messages.to_sentence
				render 'index'
			end
		else
			@order.confirmed_at = Time.now
			@order.origin_price = @order.total_price
			@order.grand_total = @order.discounted_price.to_f + @order.shipping_cost.to_f
			if @order.save
					render 'receipt'
				else
					flash[:error] = @order.errors.full_messages.to_sentence
					render 'index'
			end
		end
  end

  private
  def order_params
    params.require(:order).permit(:name, :address, :discount_code, :discounted_price, :shipping_cost)
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy, :search]

  # GET /food_items
  # GET /food_items.json
  def index
    
    if (params[:search] && params[:search].present?)
      @food_items = FoodItem.search(params[:search])
    #elsif (params[:filter] && params[:filter].present?)
    #@articles = Article.filter(params[:filter])
    else
      @food_items = FoodItem.all
    end
  end

  def searchItem
    if (params[:food_item_id] && params[:food_item_id].present?)
      @food_items = FoodItem.searchItem(params[:food_item_id])
    end
  end
  # GET /food_items/1
  # GET /food_items/1.json
  def show
    #@current_order = OrderSum.last
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :image_url, :section_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def menu
    if params[:section]
      @section = Section.where(name: params[:section]).first
    elsif params[:section_id]
      @section = Section.where(id: params[:section_id]).first
    end
  end

  def contact_us
  end
  def order
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
    def create
        @order_item = OrderItem.new order_item_param
        @order_item.order = current_order
        if @order_item.save
            redirect_to menu_path
        else
            raise "can not add to order"
        end
    end

    private
    def order_item_param
        params.require(:order_item).permit(:quantity,:food_item_id)
    end
end

app/controllers/order_sums_controller.rb
class OrderSumsController < ApplicationController
  def index
    @order_sum = OrderSum.first
    if @order_sum 
      redirect_to @order_sum
    else
      redirect_to new_order_sum_path
    end 
  end

  def new
  end

  def show
    @order_sum = OrderSum.find params[:id]
    if params[:food_item_id]
      @order_detail = OrderDetail.new(food_item_id: 123, order_sum_id: 123)
        if @order_detail.save
          @food_item = FoodItem.find params[:food_item_id]
          redirect_to new_order_sum_path
        else
          render "ERROR ADDING ITEM"
        end
    end
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/checkout/index.html.erb
<h1>Checkout</h1>
<div class="container-fluid">
<%= form_for @order, url:checkout_confirm_path, method:'post' do |f|%>
<% if @order.errors.present?%>
<div class="alert alert-danger">
<%= @order.errors.full_messages.to_sentence%>
<% @order.discount_code = nil%>
</div>
<%end%>
<div class:"form-group">
<%= f.label :name%>
<%= f.text_field :name , class:"form-control"%>
</div>
<div class:"form-group">
<%= f.label :address%>
<%= f.text_area :address , class:"form-control"%>
</div>

<table class="table">
Item List
	<% @order.order_items.each do |order_item| %>
	<tr>
	<td><%= order_item.food_item.name %></td>
		<td><%= order_item.food_item.price %></td>
    <td><%= order_item.quantity %></td>
    </tr>
    <% end %>
</table>
<div>
Total Price <%= number_to_currency @order.total_price%>
</div>
<div>
Price after discount <%= number_to_currency @order.discounted_price%>
</div>
<div class:"form-group">
<%= f.label :discount_code%>
<%= f.text_field :discount_code , class:"form-control"%>
<%#= f.submit "Apply Discount", class:"btn btn-secondary"%>
<%#= link_to "Apply Discount", checkout_path, class:"btn btn-secondary"%>
<%#= link_to "Check out", checkout_path, class:"btn btn-secondary"%>
<%#= link_to 'Apply discount', checkout_apply_discount_path, method: :post %></span>
</div>
<div class:"form-group">
<%= f.label :shipping_cost%>
<%= f.label :shipping_cost , value:"20", class:"form-control"%>
</div>
<br>
<%= f.submit "Confirm", class:"btn btn-secondary"%>
<% end %>
</div>

app/views/checkout/receipt.html.erb
<h1>Receipt</h1>
<h2>Thanks for your order. This is your receipt</h2>
<div class="container-fluid">
<%= form_for @order, url:checkout_confirm_path, method:'post' do |f|%>
<% if @order.errors.present?%>
<div class="alert alert-danger">
<%= @order.errors.full_messages.to_sentence%>
</div>
<%end%>
<div class:"form-group">
Name: <%= @order.name%>
</div>
<div class:"form-group">
Address: <%= @order.address%>
</div>
<table class="table">
Item List
	<% @order.order_items.each do |order_item| %>
	<tr>
	<td><%= order_item.food_item.name %></td>
		<td><%= order_item.food_item.price %></td>
    <td><%= order_item.quantity %></td>
    </tr>
    <% end %>
</table>
<div>
Origin Price <%= number_to_currency @order.total_price%>
</div>
<div class:"form-group">
Discount Code <%= @order.discount_code %>
</div>
<div>
Price after discount <%= number_to_currency @order.discounted_price%>
</div>
<div class:"form-group">
Shipping Cost <%= number_to_currency @order.shipping_cost%>
</div>
<div class:"form-group">
Grand Total <%= number_to_currency @order.grand_total%>
</div>
<% end %>
</div>

app/views/food_items/_food_item.html.erb
<ul class="list-group">
    <% @food_items.each do |food_item|%>
      <li class="list-group-item">
            <%= link_to food_item.name, food_item_path(food_item.id)%>
            <span class="tag tag-default tag-pill"><%= food_item.price %></span>
            <span class="btn btn-info pull-sm-right"><%= link_to 'Edit', edit_food_item_path(food_item) %></span>
            <span class="btn btn-danger pull-sm-right"><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      </li>
      <%end%>
</ul>

app/views/food_items/_form.html.erb
<%= form_for(food_item) do |f| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :section_id %>
    <%= f.text_field :section_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_item_path(@food_item.id) %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Image url</th>
      <th>Section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.image_url %></td>
        <td><%= food_item.section %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

      <div class="row">
          <div class="col-sm-6">
            <span class="tag tag-default tag-pill  pull-sm-right"><%= @food_item.price %></span>
            <p>
              <strong>Name:</strong>
              <%= @food_item.name %>
            </p>
            <p>
              <strong>Description:</strong>
              <%= @food_item.description %>
            </p>
          </div>
          <div class="col-sm-6">
              <div class="card-img">
                <%= image_tag(@food_item.image_url)%>
              </div>
          </div>
      </div>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', menu_path(section_id: @food_item.section_id) %> 
<%= form_for OrderItem.new do |f|%>
<div class="form-inline">
<div class="form-group">
<%= f.label :quantity %>
<%= f.number_field :quantity, class:"form-controller" %>
<%= f.hidden_field :food_item_id, value:@food_item.id %>
</div>
<div>
<%= f.submit "Add to order", class: "btn btn_secondary"%>
</div>
</div>
<%end%>

app/views/home/contact_us.html.erb
<h1>Contact Us</h1>
<div class="row" >
    <div class="col-sm-4">
        <address> Vesterbrogade 44, 1620 København, Denmark
        </address>
        <phone>+45 53 53 67 97</phone>
    </div>

<div class="col-sm-8">
<h4>Google map</h4>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2249.9295296906366!2d12.553172415628014!3d55.67282558053204!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4652530b299d6cc1%3A0x837d773d5a375fab!2sBonjour+Vietnam+Caf%C3%A9+%26+Restaurant!5e0!3m2!1sen!2s!4v1476349418000" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>

app/views/home/index.html.erb
<h1>Welcome to Bonjour Restaurant</h1>

app/views/home/menu.html.erb
<h1>Menu</h1>
<div class="card card-block">
You have <%= current_order.order_items.size %> item in your orders
<%= link_to "Check out", checkout_path, class:"btn btn-secondary"%>
</div>
<ul class="nav nav-pills">
  <% Section.all.each do |section|%>
  <li class="nav-item">
      <% if params[:section_id] %>
        <%= link_to section.name, menu_path(section: section.name), 
        class: "nav-link #{'active' if params[:section_id]==section.id }"%>
        <%else%>
        <%= link_to section.name, menu_path(section: section.name), 
        class: "nav-link #{'active' if params[:section]==section.name }"%>
      <%end%>
  </li>
  <%end%>
  <!-- Dropdown filter -->
<div class="btn-group">
  <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort Food By
  </button>
  <div class="dropdown-menu">
    <%= link_to 'alphabetical', menu_path(order_by: 0), class:"dropdown-item"%>
    <%= link_to 'price low to high', menu_path(order_by: 1), class:"dropdown-item"%>
    <%= link_to 'price high to low', menu_path(order_by: 2), class:"dropdown-item"%>
  </div>
</div>
</ul>
<% if @section%>
<ul class="list-group">
    <% @section.food_items.each do |food|%>
      <li class="list-group-item">
            <span class="tag tag-default tag-pill  pull-sm-right"><%= food.price %></span>
            <%= link_to food.name, food_item_path(food.id)%>
      </li>
    <%end%>
<%else%>
  <% if params[:order_by] %>
    <% if params[:order_by]=='0' %>
        <% FoodItem.order(:name).all.each do |food|%>
        <li class="list-group-item"><span class="tag tag-default tag-pill  pull-sm-right"><%= food.price %></span>
        <%= link_to food.name, food_item_path(food.id)%></li><%end%>
      <% elsif params[:order_by]=='1' %>
        <% FoodItem.order(price: :asc).all.each do |food|%>
        <li class="list-group-item"><span class="tag tag-default tag-pill  pull-sm-right"><%= food.price %></span>
        <%= link_to food.name, food_item_path(food.id)%></li><%end%>
      <% elsif params[:order_by]=='2' %>
        <% FoodItem.order(price: :desc).all.each do |food|%>
        <li class="list-group-item"><span class="tag tag-default tag-pill  pull-sm-right"><%= food.price %></span>
        <%= link_to food.name, food_item_path(food.id)%></li><%end%>
    <%end%>
  <%else%>
    <% FoodItem.all.each do |food|%>
      <li class="list-group-item">
            <span class="tag tag-default tag-pill  pull-sm-right"><%= food.price %></span>
            <%= link_to food.name, food_item_path(food.id)%>
      </li>
      <%end%>
  <%end%>
</ul>
<%end%>

app/views/home/order.html.erb
<h1>Home#order</h1>
<p>Find me in app/views/home/order.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BonjourRestaurant</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-light bg-faded">
    <a class="navbar-brand" href="/">Bonjour Restaurant</a>
  
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#"><%= link_to "Menu",menu_path%></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#"><%= link_to "Contact Us", contact_us_path%></a>
    </li>
  </ul>
  
    <%= form_tag(food_items_path, :method => 'get',id:"search-form", class:"form-inline pull-xs-right") do %>
      <%= text_field_tag :search, params[:search], placeholder:"Search", class: "form-control" %>
      <%= submit_tag "Search", class: "btn btn-outline-success"%>
    <% end %>
  
    
    
    
</nav>
<div class="container">  
	  <%= yield %>
    </div>
  </body>
</html>